### ISSUE TITLE
minishell の要件を軽く洗い直す

### ISSUE THREAD

**Issue by ntk221** [ntk221/minishell#19]
- [X] 課題要件の前半をREADME.md に記載する。

- [ ] #37

**Comment by ntk221** [comment]
pdf を読んで main ブランチのREADME.md に要件を追加するのがいいかな。

**Comment by molhot** [comment]
確かに、課題要件を無視していたｗ
どこかのタイミングで読む、もしくは読んで意見を合わせるとかいいかもですね！

**Comment by ntk221** [comment]
では，このissue は 二人で着手することにしましょうか！😄

**Comment by ntk221** [comment]
使用可能関数

readline, rl_clear_history, rl_on_new_line, rl_replace_line, rl_redisplay, add_history, printf, malloc, free, write, access, open, read, close, fork, wait, waitpid, wait3, wait4, signal, sigaction, sigemptyset, sigaddset, kill, exit, getcwd, chdir, stat, lstat, fstat, unlink, execve, strerror, perror, isatty, ttyname, ttyslot, ioctl, getenv, tcsetattr, tcgetattr, tgetent, tgetflag, tgetnum, tgetstr, tgoto, tputs

**Comment by ntk221** [comment]
exec 系のシステムコールが, execveだけなのに注意かも？
