### ISSUE TITLE
存在しないコマンドを入力した時，プロンプトに制御が戻らない

### ISSUE THREAD

**Issue by ntk221** [ntk221/minishell#26]

**Comment by ntk221** [comment]
<img width="488" alt="スクリーンショット 2022-12-26 13 06 29" src="https://user-images.githubusercontent.com/92190938/209498495-4fa9976c-a500-4fdf-a38b-5bdda3b44b90.png">

**Comment by molhot** [comment]
今回一歩目としてechoが必ず来るように考えてしまった為ですね...
この辺りはif elseでどうにかできそうですね！

**Comment by ntk221** [comment]
ft_echo の リファクタの段階で，同時に修正しました。本当は，修正履歴を残したいのですが，やり方がわからないので無理です！！！
