### ISSUE TITLE
execveの調査

### ISSUE THREAD

**Issue by ntk221** [ntk221/minishell#36]
fork() の 後には，子プロセス側で exec するのがコマンド実行のセオリーであるが，exec にはさまざまな変種がある(`man exec`を参照)。今回使用可能関数として挙げられているのは，`execve`です。

```

#include <unistd.h>
int execve(const char *path, char *const argv[], char *const envp[]);
```

https://ja.manpages.org/execve/2

```
execve("/bin/ls", argv, environ);
```
- [x] #45

**Comment by molhot** [comment]
【ナレッジ貯蔵庫】
https://progzakki.sanachan.com/program-lang/c/how-to-use-dup/　execuveを使用したコードが書かれている

**Comment by molhot** [comment]
https://linuxjm.osdn.jp/html/LDP_man-pages/man2/execve.2.html
MAN

**Comment by molhot** [comment]
execveには
実行可能なファイルパス　引数
という風に与える必要があるが、ファイルパスに実行できないものが入っているかどうかの確認が出来れば
tokenに「CMDornot]みたいなのを入れてtokenizerが作れそう
