### ISSUE TITLE
split関数の動きがおかしいかもしれない⭐️

### ISSUE THREAD

**Issue by molhot** [ntk221/minishell#66]
splitを行った時、挙動がおかしいかもしれない
ex)
t e s t
想定される解答)
t e s t
解答)
segmentation fault

**Comment by molhot** [comment]
調査します

**Comment by molhot** [comment]
普通にsplitするだけなら問題ないようなのですが
English | Japanese |
のような時になぜか挙動がおかしくなってしまう（パーサーなので、別の実装方法にしたら良さそう

**Comment by ntk221** [comment]
Codespaces 上で上記のテストケースで確認したところ同様のバグを発見できませんでした。
